(function () {
  'use strict';
  var disability = 'Disabilities';
  var design = 'Accessibility and Universal Design';
  var standards = 'Standards, Laws, and Management Strategies';
  var cards = [
    { domain: disability, term: 'Accessibility barrier', definition: 'A condition in a product, service, environment, or process that restricts a person’s participation or ability to complete a task.' },
    { domain: disability, term: 'Impairment', definition: 'A difference or loss in body function or structure. It is one aspect of disability, not a complete account of a person’s experience.' },
    { domain: disability, term: 'Disability', definition: 'A concept shaped by the interaction between a person’s characteristics and barriers in their environment; definitions also vary across legal and social contexts.' },
    { domain: disability, term: 'Medical model of disability', definition: 'A model that locates disability primarily in an individual’s impairment or health condition and often emphasizes diagnosis or treatment.' },
    { domain: disability, term: 'Social model of disability', definition: 'A model that emphasizes how social, attitudinal, and environmental barriers restrict the participation of people with impairments.' },
    { domain: disability, term: 'Interactional model of disability', definition: 'A perspective that considers disability as arising through interaction among a person, their activities, and the physical, social, and technological environment.' },
    { domain: disability, term: 'Person-first language', definition: 'Language that places the person before a disability descriptor, such as “person with a disability”; individual preferences should guide usage.' },
    { domain: disability, term: 'Identity-first language', definition: 'Language that treats disability as an identity, such as “disabled person”; some people prefer this form, so do not assume one wording suits everyone.' },
    { domain: disability, term: 'Assistive technology (AT)', definition: 'An item, system, or product used to increase, maintain, or improve functional capabilities; in digital access it can include hardware and software.' },
    { domain: disability, term: 'Screen reader', definition: 'Assistive software that conveys interface content and structure through speech, braille, or both, often using the platform accessibility APIs.' },
    { domain: disability, term: 'Screen magnification', definition: 'Software or a device feature that enlarges part or all of a display, sometimes with tracking, color, or contrast adjustments.' },
    { domain: disability, term: 'Refreshable braille display', definition: 'A device with changeable braille cells that presents text output from a computer or mobile device in tactile form.' },
    { domain: disability, term: 'Switch access', definition: 'An interaction method using one or more switches, often with scanning, to select items without conventional pointer or keyboard movements.' },
    { domain: disability, term: 'Speech recognition', definition: 'Technology that interprets spoken input to control a device or create text; it may be used as an alternative input method.' },
    { domain: disability, term: 'Augmentative and alternative communication (AAC)', definition: 'Methods and tools that support or replace spoken communication, ranging from gestures and communication boards to speech-generating devices.' },
    { domain: disability, term: 'Caption', definition: 'Synchronized text representing speech and relevant non-speech audio in audiovisual content; captions may be open or user-selectable.' },
    { domain: disability, term: 'Audio description', definition: 'Narration of important visual information in media, such as actions, settings, or on-screen text, for people who cannot see that information.' },
    { domain: disability, term: 'Temporary disability', definition: 'A short-term condition or injury that affects access, such as a broken arm that limits use of a pointing device.' },
    { domain: disability, term: 'Situational limitation', definition: 'An access constraint created by context, such as bright sunlight, loud surroundings, or holding an infant.' },
    { domain: disability, term: 'Neurodiversity', definition: 'The natural variation in human brains and minds; it includes many forms of cognitive and neurological difference and is not itself a diagnosis.' },
    { domain: disability, term: 'Cognitive accessibility', definition: 'Design practices that support people with diverse attention, memory, language, learning, and problem-solving needs.' },
    { domain: disability, term: 'Deaf culture', definition: 'A cultural and linguistic community associated with Deaf identity and signed languages; Deaf people are diverse and may or may not identify with this community.' },
    { domain: disability, term: 'Color vision deficiency', definition: 'A difference in distinguishing some colors; use labels, patterns, or other cues so meaning does not rely on color alone.' },
    { domain: disability, term: 'Fatigue and fluctuating ability', definition: 'Some people’s energy, pain, concentration, or functional abilities change over time, making flexible interactions valuable.' },
    { domain: disability, term: 'Nothing about us without us', definition: 'A disability-rights principle calling for people with disabilities to participate meaningfully in decisions that affect them.' },

    { domain: design, term: 'Universal design', definition: 'Design of products and environments to be usable by all people, to the greatest extent possible, without the need for adaptation or specialized design.' },
    { domain: design, term: 'Inclusive design', definition: 'An approach that recognizes diversity and involves people with different needs and perspectives so design choices reduce exclusion.' },
    { domain: design, term: 'Equitable use', definition: 'A universal design principle: make the design useful and marketable to people with diverse abilities without stigmatizing or disadvantaging anyone.' },
    { domain: design, term: 'Flexibility in use', definition: 'A universal design principle: accommodate a wide range of individual preferences and abilities, such as multiple input methods.' },
    { domain: design, term: 'Simple and intuitive use', definition: 'A universal design principle: make use easy to understand regardless of a user’s experience, knowledge, language skills, or concentration level.' },
    { domain: design, term: 'Perceptible information', definition: 'A universal design principle: communicate necessary information effectively to users regardless of ambient conditions or sensory abilities.' },
    { domain: design, term: 'Tolerance for error', definition: 'A universal design principle: minimize hazards and adverse consequences of accidental or unintended actions.' },
    { domain: design, term: 'Low physical effort', definition: 'A universal design principle: allow efficient, comfortable use with minimal fatigue.' },
    { domain: design, term: 'Size and space for approach and use', definition: 'A universal design principle: provide appropriate size and space for reach, manipulation, and use regardless of body size, posture, or mobility.' },
    { domain: design, term: 'POUR', definition: 'The four WCAG principles: Perceivable, Operable, Understandable, and Robust.' },
    { domain: design, term: 'Perceivable', definition: 'Information and user-interface components must be presentable to users in ways they can perceive, including through alternatives to sensory-only content.' },
    { domain: design, term: 'Operable', definition: 'User-interface components and navigation must be operable using available input methods, including keyboard access.' },
    { domain: design, term: 'Understandable', definition: 'Information and operation of the user interface must be understandable, with predictable behavior and clear instructions.' },
    { domain: design, term: 'Robust', definition: 'Content should be interpreted reliably by a wide variety of user agents, including assistive technologies.' },
    { domain: design, term: 'Semantic HTML', definition: 'HTML elements chosen for their meaning and built-in behavior, such as headings, buttons, and labeled form controls.' },
    { domain: design, term: 'Alternative text', definition: 'A text equivalent for an image’s purpose or information; decorative images usually use an empty alternative so they can be skipped.' },
    { domain: design, term: 'Keyboard accessibility', definition: 'The ability to operate functionality through a keyboard interface without requiring specific timings for individual keystrokes.' },
    { domain: design, term: 'Visible focus indicator', definition: 'A visible cue showing which interactive element currently has keyboard focus.' },
    { domain: design, term: 'Reflow', definition: 'Presenting content without loss of information or functionality and without requiring two-dimensional scrolling for typical text content at narrow viewports or high zoom.' },
    { domain: design, term: 'Contrast ratio', definition: 'A relative measure comparing the luminance of foreground and background colors; WCAG defines minimum ratios for many text and interface uses.' },
    { domain: design, term: 'Name, role, value', definition: 'Accessible information that allows assistive technologies to identify a user-interface component, what it is, and its current state or value.' },
    { domain: design, term: 'Programmatic label', definition: 'A label associated in code with a form control so that its purpose is conveyed to browsers and assistive technologies.' },
    { domain: design, term: 'Error identification', definition: 'Clearly describing an input error in text and identifying the affected item so users can understand and correct it.' },
    { domain: design, term: 'Skip link', definition: 'A mechanism near the start of a page that lets keyboard users bypass repeated blocks, such as site navigation.' },
    { domain: design, term: 'Reduced motion', definition: 'A user preference for limiting nonessential movement; interfaces should respect the preference and avoid motion that can cause discomfort.' },

    { domain: standards, term: 'W3C', definition: 'The World Wide Web Consortium, an international community that develops web standards and guidelines.' },
    { domain: standards, term: 'WAI', definition: 'The W3C Web Accessibility Initiative, which develops standards, guidelines, and resources to help make the web accessible.' },
    { domain: standards, term: 'WCAG', definition: 'The Web Content Accessibility Guidelines, a W3C Recommendation with testable success criteria for accessible web content.' },
    { domain: standards, term: 'WCAG conformance level', definition: 'A level—A, AA, or AAA—that groups success criteria; conformance to a higher level includes applicable criteria at lower levels.' },
    { domain: standards, term: 'WCAG success criterion', definition: 'A testable requirement in WCAG used to evaluate a specific aspect of web content accessibility.' },
    { domain: standards, term: 'Conformance claim', definition: 'A statement that content meets applicable WCAG conformance requirements; a claim should accurately describe its scope and standard version.' },
    { domain: standards, term: 'Web Accessibility Initiative - Accessible Rich Internet Applications (WAI-ARIA)', definition: 'A W3C specification for adding accessibility semantics to web content, especially custom widgets; it supplements rather than replaces native HTML.' },
    { domain: standards, term: 'U.S. Americans with Disabilities Act (ADA)', definition: 'A United States civil rights law prohibiting disability discrimination in covered contexts; its application depends on legal interpretation and context.' },
    { domain: standards, term: 'Section 508', definition: 'A provision of the U.S. Rehabilitation Act requiring federal agencies to make covered information and communication technology accessible.' },
    { domain: standards, term: 'Rehabilitation Act Section 504', definition: 'A U.S. law prohibiting disability discrimination in programs or activities receiving federal financial assistance and certain federal contexts.' },
    { domain: standards, term: 'UN Convention on the Rights of Persons with Disabilities (CRPD)', definition: 'An international human rights treaty that promotes, protects, and ensures the full and equal enjoyment of human rights by persons with disabilities.' },
    { domain: standards, term: 'European Accessibility Act (EAA)', definition: 'A European Union directive establishing accessibility requirements for specified products and services, implemented through national laws.' },
    { domain: standards, term: 'EN 301 549', definition: 'A European harmonized standard specifying accessibility requirements for information and communication technology products and services.' },
    { domain: standards, term: 'Accessibility conformance report (ACR)', definition: 'A report describing how a product or service conforms to accessibility requirements, often using the VPAT format.' },
    { domain: standards, term: 'Voluntary Product Accessibility Template (VPAT)', definition: 'A template used to create an accessibility conformance report; a completed VPAT reports conformance and does not itself certify a product.' },
    { domain: standards, term: 'Accessibility maturity model', definition: 'A framework for assessing how consistently an organization incorporates accessibility across leadership, processes, skills, and products.' },
    { domain: standards, term: 'Accessibility policy', definition: 'An organizational statement of commitments, responsibilities, and expectations for accessibility.' },
    { domain: standards, term: 'Accessibility program owner', definition: 'A designated leader or team responsible for coordinating accessibility goals, resources, processes, and progress across an organization.' },
    { domain: standards, term: 'Accessibility audit', definition: 'A structured evaluation of a product or service against defined criteria to identify accessibility issues and strengths.' },
    { domain: standards, term: 'Automated accessibility testing', definition: 'Tool-assisted checks that can detect some measurable issues but cannot determine every barrier or replace human evaluation.' },
    { domain: standards, term: 'Manual accessibility testing', definition: 'Human evaluation such as keyboard review, screen-reader testing, visual inspection, and assessment of content and interaction.' },
    { domain: standards, term: 'User-centered accessibility testing', definition: 'Research and usability evaluation with people with disabilities to understand real use and uncover barriers.' },
    { domain: standards, term: 'Accessibility procurement', definition: 'Including accessibility requirements, documentation, evaluation, and remediation expectations when selecting or purchasing products and services.' },
    { domain: standards, term: 'Remediation plan', definition: 'A prioritized, assigned, and time-bounded plan for correcting identified accessibility barriers and verifying the fixes.' },
    { domain: standards, term: 'Accessibility statement', definition: 'A public description of an organization’s accessibility commitment, scope, known limitations, and means to provide feedback or request help.' }
  ];
  window.CPACC_FLASHCARDS = cards;
}());
